### ISSUE TITLE
ImportError: No module named 'algorithms'

### ISSUE THREAD

**Issue by Jerry-Jie-Xie** [IvanoLauriola/MKLpy#1]
When I try to run the files in the test folder, it gives me the following error. 
Can you help me check what the problem is? Thank you.

 runfile('E:/Anaconda3/Lib/site-packages/MKLpy/test/check_list.py', wdir='E:/Anaconda3/Lib/site-packages/MKLpy/test')
Traceback (most recent call last):

  File "<ipython-input-9-f9d67e0bbc52>", line 1, in <module>
    runfile('E:/Anaconda3/Lib/site-packages/MKLpy/test/check_list.py', wdir='E:/Anaconda3/Lib/site-packages/MKLpy/test')

  File "E:\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 880, in runfile
    execfile(filename, namespace)

  File "E:\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "E:/Anaconda3/Lib/site-packages/MKLpy/test/check_list.py", line 46, in <module>
    from MKLpy.lists import kernel_list, HPK_generator, SFK_generator

  File "E:\Anaconda3\lib\site-packages\MKLpy\__init__.py", line 39, in <module>
    import algorithms,lists,metrics,test,utils

ImportError: No module named 'algorithms'

**Comment by IvanoLauriola** [comment]
Hy,
a more stable version of MKLpy is available on PyPI repository, this is an old version for developement and testing.

https://pypi.python.org/pypi/MKLpy

It is possible to install MKLpy using pip command:
`pip install MKLpy`

**Comment by Jerry-Jie-Xie** [comment]
Thanks Ivano, I will check it later.
